---
- name: Check AuroSphere Patch Installation
  hosts: DPDYPHGFDAY0536
  gather_facts: false

  tasks:

    - name: Check patch agent service
      ansible.windows.win_shell: |
        Get-Service windows-agent-patch |
        Select-Object Name, Status, StartType
      register: service
      changed_when: false

    - name: Check KB5121003
      ansible.windows.win_shell: |
        $p = Get-HotFix -Id KB5121003 -ErrorAction SilentlyContinue

        if ($p) {
            "KB5121003 INSTALLED"
            "InstalledOn: $($p.InstalledOn)"
        }
        else {
            "KB5121003 NOT INSTALLED"
        }
      register: patch
      changed_when: false

    - name: Check patch history
      ansible.windows.win_shell: |
        $file = "C:\ProgramData\windows-agent-patch\patch\history.json"

        if (Test-Path $file) {
            Get-Content $file
        }
        else {
            "history.json NOT FOUND"
        }
      register: history
      changed_when: false

    - name: Check agent log
      ansible.windows.win_shell: |
        $log = "C:\ProgramData\windows-agent\logs\agent.log"

        if (Test-Path $log) {
            Get-Content $log |
            Select-String "KB5121003|install|wusa|error|failed"
        }
        else {
            "agent.log NOT FOUND"
        }
      register: logs
      changed_when: false

    - name: Display result
      debug:
        msg:
          - "SERVICE:"
          - "{{ service.stdout_lines }}"
          - "PATCH:"
          - "{{ patch.stdout_lines }}"
          - "HISTORY:"
          - "{{ history.stdout_lines }}"
          - "LOG:"
          - "{{ logs.stdout_lines }}"
