---
- name: Remove AuroSphere Patch Agent EXE
  hosts: DPDYPHGFDAY0536
  gather_facts: false

  vars:
    agent_exe: 'C:\Program Files\CustomAgent\windows-agent-patch\windows-agent-patch.exe'

  tasks:

    - name: Stop AuroSphere patch service
      ansible.windows.win_service:
        name: windows-agent-patch
        state: stopped
      failed_when: false

    - name: Remove old AuroSphere patch agent EXE
      ansible.windows.win_file:
        path: "{{ agent_exe }}"
        state: absent

    - name: Verify old EXE removed
      ansible.windows.win_stat:
        path: "{{ agent_exe }}"
      register: exe_check

    - name: Display result
      ansible.builtin.debug:
        msg: "Old AuroSphere patch EXE exists: {{ exe_check.stat.exists }}"
